
pipeline:
  name: HelloWorldPipeline
  identifier: HelloWorldPipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: kppriyajai
        repoName: Simple-Node-App
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: HelloWorldStage
        identifier: HelloWorldStage
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Print Hello World
                  identifier: Print_Hello_World
                  spec:
                    shell: Sh
                    command: echo "Hello, World!"
